version: '3'
services:
  api:
    image: pi0neerpat/dao-preview
    restart: always
    ports:
      - '8910:8910' # http
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    env_file:
      - .env
