name: Chromatic

on:
  push:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache "node_modules"
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules_${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: web/public/storybook
          exitOnceUploaded: true
